# Build `MESH` Model Setup for Calibration of CAMELS-SPAT basins

We use the `MESHFlow` Python package to build a `MESH` model setup for the Canada and transboundary river basins.

Let's start by importing the necessary libraries:

In [1]:
# import necessary libraries
import meshflow # version: meshflow-0.1.0.dev6

import os # python 3.10.2

Now, let's provide necessary information to set up the `MESH` model:

In [4]:
# main work path - modify
work_path = os.path.abspath(os.path.join(os.getcwd(), '..', '..', '..'))

# modify each segment to match your settings
config = {
    'riv': os.path.join(work_path, 'github-repos/community-workflows/1-geofabric/CAMELS-SPAT/merged_lamped', 'agg_CAMELS-MERIT_CanTrans_rivers.shp'),
    'cat': os.path.join(work_path, 'github-repos/community-workflows/1-geofabric/CAMELS-SPAT/merged_lamped', 'agg_CAMELS-MERIT_CanTrans_subbasins.shp'),
    'landcover': os.path.join(work_path, 'scratch/cantrans-models/gistool-outputs/camels-spat-outputs', 'CanTrans_model_stats_NA_NALCMS_landcover_2020_30m.csv'),
    'forcing_files': os.path.join(work_path, 'scratch/cantrans-models/camels-casr3p2-easymore-outputs'),
    'forcing_vars': {
        "precipitation": "CaSR_v3.1_A_PR0_SFC",
        "shortwave_radiation": "CaSR_v3.1_P_FB_SFC",
        "longwave_radiation": "CaSR_v3.1_P_FI_SFC",
        "air_pressure": "CaSR_v3.1_P_P0_SFC",
        "specific_humidity": "CaSR_v3.1_P_HU_09975",
        "air_temperature": "CaSR_v3.1_P_TT_09975",
        "wind_speed": "CaSR_v3.1_P_UVC_09975",
    },        
    'forcing_units': {
        'precipitation': 'm/s',
        'shortwave_radiation': 'W/m^2',
        'longwave_radiation': 'W/m^2',
        'air_pressure': 'pascal',
        'specific_humidity': 'kg/kg',
        'air_temperature': 'kelvin',
        'wind_speed': 'm/s',
    },
    'main_id': 'COMID',
    'ds_main_id': 'NextDownID',
    'landcover_classes': {
        0: 'Unknown',
        1: 'Temperate or sub-polar needleleaf forest',
        2: 'Sub-polar taiga needleleaf forest',
        3: 'Tropical or sub-tropical broadleaf evergreen forest',
        4: 'Tropical or sub-tropical broadleaf deciduous forest',
        5: 'Temperate or sub-polar broadleaf deciduous forest',
        6: 'Mixed forest',
        7: 'Tropical or sub-tropical shrubland',
        8: 'Temperate or sub-polar shrubland',
        9: 'Tropical or sub-tropical grassland',
        10: 'Temperate or sub-polar grassland',
        11: 'Sub-polar or polar shrubland-lichen-moss',
        12: 'Sub-polar or polar grassland-lichen-moss',
        13: 'Sub-polar or polar barren-lichen-moss',
        14: 'Wetland',
        15: 'Cropland',
        16: 'Barren lands',
        17: 'Urban',
        18: 'Water',
        19: 'Snow and Ice',
    },
    'ddb_vars': {
        'river_slope': 'slope',
        'river_length': 'lengthkm',
        'river_class': 'order'
    },
    'ddb_units': {
        'river_slope': 'dimensionless',
        'river_length': 'kilometer',
        'river_class': 'dimensionless'
    },
    'ddb_min_values': {
        'ChnlSlope': 1e-10, # in case there are 0s in the `rivers` Shapefile, we need minimums for certain variables
        'ChnlLength': 1e-3,
        'GridArea': 1e-3,
    },
    'settings': {
        'core': {
            'forcing_files': 'multiple',
            'forcing_start_date': '1980-12-30 00:00:00',
            'simulation_start_date': '1980-12-30 12:00:00',
            'simulation_end_date': '1980-12-31 18:00:00',
            'forcing_time_zone': 'UTC',
            # 'model_time_zone': 'America/Edmonton',
            'output_path': 'results',
        },
        'class_params': {
            'measurement_heights': {
                'wind_speed': 20,
                'specific_humidity': 20,
                'air_temperature': 20,
                'roughness_length': 50,
            },
            'copyright': {
                'author': 'ECCC-NAS',
                'location': 'ECCC-NAS',
            },
            'grus': {
                0: 'needleleaf',
                1: {
                    'class': 'needleleaf',
                    'LNZ0': -1.4,
                },
                2: 'needleleaf',
                3: 'broadleaf',
                4: 'broadleaf',
                5: {
                    'class': 'broadleaf',
                    'rOot': 4,
                },
                6: 'broadleaf',
                7: 'grass',
                8: 'grass',
                9: 'grass',
                10: 'grass',
                11: 'grass',
                12: 'grass',
                13: 'grass',
                14: 'water',
                15: 'crops',
                16: 'barrenland',
                17: 'urban',
                18: 'water',
                19: 'water',
            },
        },
        'hydrology_params': {
            'routing': [
                {
                    'R2N': 0.3
                },
            ],
            'hydrology': {
                5: {
                    'ZSNL': 2,
                },
            },
        },
        'run_options': {},
    },
    'gru_dim': 'NGRU', # change to `NGRU` for 'MESH>=r1860', keep for 'MESH<=1860', for example for r1813.
    'hru_dim': 'subbasin',    
    'outlet_value': 0,
}

We can build an "instance" of the workflow class:

In [5]:
exp1 = meshflow.MESHWorkflow(**config)

And, we can run it using:

In [8]:
exp1.run(save_path=os.path.join(work_path, 'camels_mesh_outputs'))

/home/zelalem/virtual-envs/scienv/lib/python3.11/site-packages/meshflow/core.py:775: UserWarning: Since multiple forcing files are needed, each file will be processed and saved during initialization.
  warnings.warn(

ValueError: item CaSR_v3.1_A_PR0_SFC defined in `units` cannot be found in `variables`

In [9]:
exp1.save(output_dir=os.path.join(work_path, 'camels_mesh_outputs'))

AttributeError: 'MESHWorkflow' object has no attribute 'class_text'

Sort the geofabric based on the drainage database rank prepared in advance, in order to reduce computation during the model-agnostic step. This pre-sorting also eliminates the need to re-sort the remapped forcing data from Easymore during the model-specific process.

In [22]:
import os # built-in Python 3.10.2
import geopandas as gpd # version 0.14.3
import xarray as xr
import pandas as pd

# === Configuration ===
output_path = '/home/zelalem/github-repos/community-workflows/1-geofabric/CAMELS-SPAT/merged_lamped'
agg_basin = gpd.read_file(os.path.join(output_path, 'agg_CAMELS-MERIT_CanTrans_subbasins.shp'))
agg_river = gpd.read_file(os.path.join(output_path, 'agg_CAMELS-MERIT_CanTrans_rivers.shp'))
rank_column = "Rank"                       # Name of the column to sort by
ddb = xr.open_dataset(os.path.join('/home/zelalem/github-repos/camels_mesh_outputs', 'MESH_drainage_database.nc'))[['subbasin', 'Rank', 'Next']]

# This flattens the data into tabular form
df_netcdf = ddb.to_dataframe().reset_index()

# --- Merge on subbasin/COMID ---
agg_basin = agg_basin.merge(df_netcdf, left_on='COMID', right_on='subbasin')
agg_river = agg_river.merge(df_netcdf, left_on='COMID', right_on='subbasin')

# === Sort by the Rank column and drop extra column===
agg_basin_sorted = agg_basin.sort_values(by=rank_column, ascending=True)
agg_river_sorted = agg_river.sort_values(by=rank_column, ascending=True)
agg_basin_sorted = agg_basin_sorted.drop(columns=['subbasin'])
agg_river_sorted = agg_river_sorted.drop(columns=['subbasin'])

# if integer doesnot work convert them into string
#agg_basin_sorted["COMID"] = agg_basin_sorted["COMID"].astype(str)
#agg_river_sorted["COMID"] = agg_river_sorted["COMID"].astype(str)
#agg_river_sorted["NextDownID"] = agg_river_sorted["NextDownID"].astype(str)

# === Save to new shapefile ===
agg_basin_sorted.to_file(os.path.join(output_path, 'sorted_agg_CAMELS-MERIT_CanTrans_subbasins.shp'))
agg_river_sorted.to_file(os.path.join(output_path, 'sorted_agg_CAMELS-MERIT_CanTrans_rivers.shp'))

In [23]:
agg_basin_sorted

,COMID,unitarea,uparea,Mask,Has_Gauge,StationID,geometry,Rank,Next,lat,lon
83,71003233,127.065982,127.065973,0,0,None,"MULTIPOLYGON (((-95.19375 57.64542, -95.19375 ...",1.0,5.0,57.702111,-95.116528
101,71003891,117.365172,117.365171,0,0,None,"POLYGON ((-95.17375 57.62958, -95.17375 57.627...",2.0,6.0,57.551787,-95.157236
97,71003737,104.206073,104.206075,0,0,None,"MULTIPOLYGON (((-94.93708 57.38125, -94.93625 ...",3.0,6.0,57.468210,-94.942311
77,71003167,115.945294,115.945293,0,0,None,"POLYGON ((-94.62208 57.60958, -94.62125 57.609...",4.0,7.0,57.609820,-94.516637
82,71003214,106.043474,233.109448,0,0,None,"POLYGON ((-95.02042 57.61458, -95.02125 57.614...",5.0,9.0,57.652645,-95.008390
...,...,...,...,...,...,...,...,...,...,...,...
6670,8300617102,151.210108,6352.822735,2,1,10PC005,"MULTIPOLYGON (((-113.68458 66.20792, -113.6845...",6783.0,0.0,66.232300,-113.812023
6718,8301608302,101.012743,5831.711261,2,1,06JB001,"POLYGON ((-105.33708 63.59208, -105.33625 63.5...",6784.0,0.0,63.598309,-105.295182
6755,84006587,187.110031,1691.472627,2,1,10TF001,"MULTIPOLYGON (((-105.26125 69.13292, -105.2612...",6785.0,0.0,69.211807,-105.112973
6786,85009406,191.439761,3078.514161,2,1,10UH001,"POLYGON ((-68.59375 63.81208, -68.59375 63.811...",6786.0,0.0,63.899401,-68.604938
2030,71047086,195.212724,6790.504748,2,1,05057000,"POLYGON ((-97.88958 47.51208, -97.89042 47.512...",6787.0,0.0,47.490524,-97.993278

In [24]:
ddb

        subbasin    Rank  Next        lat         lon
0       71003233     1.0   5.0  57.702111  -95.116528
1       71003891     2.0   6.0  57.551787  -95.157236
2       71003737     3.0   6.0  57.468210  -94.942311
3       71003167     4.0   7.0  57.609820  -94.516637
4       71003214     5.0   9.0  57.652645  -95.008390
...          ...     ...   ...        ...         ...
6782  8300617102  6783.0   0.0  66.232300 -113.812023
6783  8301608302  6784.0   0.0  63.598309 -105.295182
6784    84006587  6785.0   0.0  69.211807 -105.112973
6785    85009406  6786.0   0.0  63.899401  -68.604938
6786    71047086  6787.0   0.0  47.490524  -97.993278

[6787 rows x 5 columns]

In [25]:
ddb = xr.open_dataset(os.path.join('/home/zelalem/github-repos/camels_mesh_outputs', 'MESH_drainage_database.nc'))[['subbasin', 'Rank', 'Next', 'ChnlSlope']]

In [27]:
df_netcdf = ddb.to_dataframe().reset_index()

In [31]:
df_netcdf["ChnlSlope"].min()

0.0